plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
      releaseRules:
        - type: 'feat'
          release: 'minor'
        - type: 'fix'
          release: 'patch'
        - type: 'perf'
          release: 'patch'
        - type: 'docs'
          release: false
        - type: 'style'
          release: false
        - type: 'refactor'
          release: 'patch'
        - type: 'test'
          release: false
        - type: 'build'
          release: 'patch'
        - type: 'ci'
          release: false
        - type: 'chore'
          release: false
        - type: 'revert'
          release: 'patch'
      parserOpts:
        headerPattern: "^(\\w*)(?:\\((.*)\\))?: (.*)$"
        headerCorrespondence:
          - 'type'
          - 'scope'
          - 'subject'
        noteKeywords:
          - 'BREAKING CHANGE'
          - 'BREAKING CHANGES'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - '@semantic-release/npm'
  - - '@semantic-release/git'
    - assets:
        - 'CHANGELOG.md'
        - 'package.json'
  - '@semantic-release/github'
