name: 'Install'
description: 'Setup Node.js, install pnpm, and install project dependencies'

inputs:
  pnpm-version:
    description: 'The version of pnpm to install'
    required: false
    default: '9'
  node-version:
    description: 'The version of Node.js to use'
    required: false
    default: 'lts/*'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      id: install-pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Set Node.js version to ${{ inputs.node-version }}
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --prefer-frozen-lockfile=false
