name: Quality Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  workflow_dispatch:

env:
  NODE_VERSION: 22.14.0
  PNPM_VERSION: 9.15.6

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Run TypeScript type check
        run: pnpm type-check:ci

  test:
    runs-on: ubuntu-latest
    needs: [type-check]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Vitest and coverage
        run: pnpm test:coverage
        env:
          CI: true

  eslint:
    runs-on: ubuntu-latest
    needs: [type-check]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Run ESLint
        run: pnpm lint:ci

  prettier:
    runs-on: ubuntu-latest
    needs: [type-check, eslint]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Prettier
        run: pnpm format:ci

  build:
    runs-on: ubuntu-latest
    needs: [type-check, test, eslint, prettier]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Build
        run: pnpm build
