name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  NODE_VERSION: 20.17.0
  PNPM_VERSION: 9
  HUSKY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}
          husky: ${{ env.HUSKY }}

      - name: Build
        run: pnpm build

      - name: Check if release is needed
        run: |
          if ! npx semantic-release --dry-run; then
            echo "No release needed, skipping."
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
